<?php

/**
 * Constants autogenerated by Pythonic\Typing\Types
 */
declare(strict_types=1);
/**
 * The bool type
 */
define('bool', 'bool');
/**
 * The float|double Type
 */
define('float', 'float');
/**
 * The int|integer type
 */
define('int', 'int');
/**
 * The string|Stringable type
 */
define('str', 'string');
/**
 * The string|Stringable type
 */
define('string', 'string');
/**
 * The None|null type
 */
define('NoneType', 'NoneType');
/**
 * The NotImplementedType type
 */
define('NotImplemented', 'NotImplementedType');
/**
 * The array type
 */
define('ArrayType', 'array');
/**
 * The base pythonic Object_ type
 * is_object($obj) !== isinstance($obj, object)
 */
define('object', 'object');

